# Generated by Django 6.0.4 on 2026-04-21 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField()),
                ('url_foto_falla', models.URLField(max_length=500)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10, null=True)),
                ('estado_ticket', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado a Técnico'), ('CERRADO', 'Resuelto / Cerrado')], default='PENDIENTE', max_length=15)),
                ('diagnostico_cierre', models.TextField(blank=True, null=True)),
                ('url_foto_cierre', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory_service.equipo')),
            ],
        ),
    ]
