"""
Django settings for InnovaSolutionMVPGestionActivos project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0c@$vqz22g@07$hq4hoa_gn+k@nbu&7qxmkw*ydfb32z)q22&#'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-0c@$vqz22g@07$hq4hoa_gn+k@nbu&7qxmkw*ydfb32z)q22&#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #APIs
    'users_service',
    'inventory_service',
    'tickets_service',
    ######
    # CORS y herramientas
    'corsheaders',
    'rest_framework.authtoken',
    
    
    # Core Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # AUTENTICACION 
    'rest_framework',
    'django.contrib.sites',
    
    # Autenticación y Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # <-- El proveedor de Google
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

SITE_ID= 1
# USUARIO PERSONALIZADO (Módulo A)
AUTH_USER_MODEL = 'users_service.User'

MIDDLEWARE = [
   'corsheaders.middleware.CorsMiddleware',  # Debe ir lo más arriba posible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # AUTENTICACION GOOGLE 
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'InnovaSolutionMVPGestionActivos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InnovaSolutionMVPGestionActivos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'es-co' # Cambiado a español
TIME_ZONE = 'America/Bogota' # Configurado para tu zona horaria
USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = 'static/'


# --- CONFIGURACIÓN DE SEGURIDAD Y JWT ---

# Variable que usamos en views.py para validar el token de Google
GOOGLE_OAUTH2_CLIENT_ID = os.getenv('GOOGLE_OAUTH2_CLIENT_ID')

# Configuración de CORS para permitir a React
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# Soluciona problemas de popups con Google Auth
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'


# --- CONFIGURACIÓN DE ALLAUTH / GOOGLE ---

SOCIALACCOUNT_ADAPTER = 'users_service.adapters.CustomSocialAccountAdapter'
# 1. Le decimos a allauth que confíe en la configuración de este archivo
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Conectamos las credenciales de tu compañero aquí
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH2_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET'),
            'key': ''
        },
        # Qué datos le vamos a pedir a Google
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
# ==========================================
# CONFIGURACIÓN DE JWT 
# ==========================================

# 1. Habilitar JWT para dj-rest-auth
REST_USE_JWT = True

# 2. Parametrizar el ciclo de vida del token
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), 
}

# 3. Definir JWT como clase de autenticación por defecto en DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    )
}
# 2. Obligamos al sistema a usar la sesión de email 
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'