# Generated by Django 6.0.4 on 2026-04-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='sede_bloque',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
