# Generated by Django 6.0.4 on 2026-04-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('fecha_compra', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=20)),
            ],
        ),
    ]
