# Generated by Django 6.0.4 on 2026-04-21 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_service', '0001_initial'),
        ('users_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipos', to='users_service.area'),
        ),
    ]
